let open      = document.getElementById('open-btn'),
		name      = document.getElementsByClassName('name'),
		budget    = document.getElementsByClassName('budget'),
		goods     = document.getElementsByClassName('goods'),
		items     = document.getElementsByClassName('items'),
		employers = document.getElementsByClassName('employers'),
		discount  = document.getElementsByClassName('discount'),
		isOpen    = document.getElementsByClassName('isopen'),
		item      = document.getElementsByClassName('goods-item'),
		btn 			= document.getElementsByTagName('button'),	
		choose		= document.querySelector('.choose-item'),
		time		  = document.querySelector('.time-value'),
		budg		  = document.querySelector('.count-budget-value'),
		empItem   =document.querySelectorAll('.hire-employers-item');
console.log(item); 
